activation_threshold: 170
automatic_learning_rate: false
learning_rate: 0.7
motion_detect_debug_contours: false
motion_detect_detectionLimit: 2
motion_detect_dilation: 7
motion_detect_erosion: 2
motion_detect_max_area: 5000
motion_detect_min_area: 60
motion_detect_shadows: false
moving_average_weight: 0.3
     